python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 254, in <module>
    run.start()
  File "core/run/run_stats.py", line 81, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 27, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 77, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 256, in <module>
    run.start()
  File "core/run/run_stats.py", line 83, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 27, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 77, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 256, in <module>
    run.start()
  File "core/run/run_stats.py", line 83, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 27, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 77, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 83, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 27, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 77, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 83, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 28, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 77, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 83, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 29, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 77, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 83, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 29, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 78, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 83, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 29, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 78, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 83, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 29, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 78, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 83, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 29, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 78, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 83, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 29, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 78, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 83, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 29, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 78, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 83, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 29, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 78, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 83, in start
    self.learner.set_task(self.task)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 29, in set_task
    self.network = self.network_cls(n_obs=task.n_inputs, n_outputs=task.n_outputs).to(self.device)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/network/fcn_relu.py", line 78, in __init__
    super(ConvolutionalNetworkReLUWithHooks, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 117, in start
    output = self.learner.predict(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 20, in predict
    output = self.network(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [6, 3, 5, 5], but got 2-dimensional input of size [1, 784] instead
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 255, in <module>
    run.start()
  File "core/run/run_stats.py", line 115, in start
    output = self.learner.predict(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 20, in predict
    output = self.network(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [6, 3, 5, 5], but got 2-dimensional input of size [1, 784] instead
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 255, in <module>
    run.start()
  File "core/run/run_stats.py", line 115, in start
    output = self.learner.predict(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 20, in predict
    output = self.network(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [6, 3, 5, 5], but got 2-dimensional input of size [1, 784] instead
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 256, in <module>
    run.start()
  File "core/run/run_stats.py", line 116, in start
    output = self.learner.predict(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 20, in predict
    output = self.network(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [6, 3, 5, 5], but got 2-dimensional input of size [1, 784] instead
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 115, in start
    output = self.learner.predict(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 20, in predict
    output = self.network(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [6, 3, 5, 5], but got 2-dimensional input of size [1, 784] instead
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 116, in start
    output = self.learner.predict(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 20, in predict
    output = self.network(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [6, 3, 5, 5], but got 2-dimensional input of size [1, 784] instead
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 256, in <module>
    run.start()
  File "core/run/run_stats.py", line 115, in start
    output = self.learner.predict(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 20, in predict
    output = self.network(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [6, 3, 5, 5], expected input[1, 1, 28, 28] to have 3 channels, but got 1 channels instead
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 256, in <module>
    run.start()
  File "core/run/run_stats.py", line 115, in start
    output = self.learner.predict(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 20, in predict
    output = self.network(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [6, 3, 5, 5], expected input[1, 1, 28, 28] to have 3 channels, but got 1 channels instead
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 256, in <module>
    run.start()
  File "core/run/run_stats.py", line 115, in start
    output = self.learner.predict(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 20, in predict
    output = self.network(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [6, 3, 5, 5], expected input[1, 1, 28, 28] to have 3 channels, but got 1 channels instead
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 116, in start
    output = self.learner.predict(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 20, in predict
    output = self.network(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [6, 3, 5, 5], expected input[1, 1, 28, 28] to have 3 channels, but got 1 channels instead
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 116, in start
    output = self.learner.predict(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 20, in predict
    output = self.network(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x256 and 400x120)
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 116, in start
    output = self.learner.predict(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 20, in predict
    output = self.network(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x256 and 400x120)
 

python3 core/run/run_stats.py --task input_permuted_mnist_stats --learner baseline --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network conv_mnist --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 257, in <module>
    run.start()
  File "core/run/run_stats.py", line 116, in start
    output = self.learner.predict(input)
  File "/home/cpinkl/anaconda3/envs/upgd/lib/python3.7/site-packages/core/learner/learner.py", line 24, in predict
    return output
UnboundLocalError: local variable 'output' referenced before assignment
 

