python3 core/run/run_stats.py --task label_permuted_cifar10_stats --learner upgd_fo_global --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network convolutional_network_relu_with_hooks --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 219, in <module>
    run.start()
  File "core/run/run_stats.py", line 170, in start
    self.save_model(f"/work/scratch/yumi/model_{self.learner.name}_{self.task_name}_{i}.pth")
  File "core/run/run_stats.py", line 37, in save_model
    "optimizer_state_dict": self.learner.optimizer(self.learner.parameters).state_dict(),
  File "/home/yumkim/miniconda3/envs/upgdnew/lib/python3.7/site-packages/core/optim/weight_upgd/first_order.py", line 76, in __init__
    names, params = zip(*params)
ValueError: not enough values to unpack (expected 2, got 0)
 

python3 core/run/run_stats.py --task label_permuted_cifar10_stats --learner upgd_fo_global --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network convolutional_network_relu_with_hooks --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 219, in <module>
    run.start()
  File "core/run/run_stats.py", line 170, in start
    self.save_model(f"/work/scratch/yumi/model_{self.learner.name}_{self.task_name}_{i}.pth")
  File "core/run/run_stats.py", line 37, in save_model
    "optimizer_state_dict": self.learner.optimizer(self.learner.parameters).state_dict(),
  File "/home/yumkim/miniconda3/envs/upgdnew/lib/python3.7/site-packages/core/optim/weight_upgd/first_order.py", line 76, in __init__
    names, params = zip(*params)
ValueError: not enough values to unpack (expected 2, got 0)
 

python3 core/run/run_stats.py --task label_permuted_cifar10_stats --learner upgd_fo_global --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network convolutional_network_relu_with_hooks --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 220, in <module>
    run.start()
  File "core/run/run_stats.py", line 169, in start
    self.save_model(f"/work/scratch/yumi/model_{self.learner.name}_{self.task_name}_{i}.pth")
  File "core/run/run_stats.py", line 37, in save_model
    "optimizer_state_dict": self.learner.optimizer(self.learner.parameters).state_dict(),
  File "/home/yumkim/miniconda3/envs/upgdnew/lib/python3.7/site-packages/core/optim/weight_upgd/first_order.py", line 76, in __init__
    names, params = zip(*params)
ValueError: not enough values to unpack (expected 2, got 0)
 

python3 core/run/run_stats.py --task label_permuted_cifar10_stats --learner upgd_fo_global --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network convolutional_network_relu_with_hooks --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 222, in <module>
    run.start()
  File "core/run/run_stats.py", line 170, in start
    self.save_model(f"/work/scratch/yumi/model_{self.learner.name}_{self.task_name}_{i}.pth")
  File "core/run/run_stats.py", line 37, in save_model
    "optimizer_state_dict": self.learner.optimizer(self.learner.parameters).state_dict(),
  File "/home/yumkim/miniconda3/envs/upgdnew/lib/python3.7/site-packages/core/optim/weight_upgd/first_order.py", line 76, in __init__
    names, params = zip(*params)
ValueError: not enough values to unpack (expected 2, got 0)
 

python3 core/run/run_stats.py --task label_permuted_cifar10_stats --learner upgd_fo_global --seed 19 --lr 0.01 --beta_utility 0.999 --sigma 0.001 --weight_decay 0.0 --network convolutional_network_relu_with_hooks --n_samples 1000000 
Traceback (most recent call last):
  File "core/run/run_stats.py", line 224, in <module>
    try:
  File "core/run/run_stats.py", line 83, in start
    for i in range(self.n_samples):
  File "/home/yumkim/miniconda3/envs/upgdnew/lib/python3.7/site-packages/core/task/label_permuted_cifar10.py", line 29, in __next__
    return next(self.iterator)
  File "/home/yumkim/miniconda3/envs/upgdnew/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/yumkim/miniconda3/envs/upgdnew/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/yumkim/miniconda3/envs/upgdnew/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yumkim/miniconda3/envs/upgdnew/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yumkim/miniconda3/envs/upgdnew/lib/python3.7/site-packages/torchvision/datasets/cifar.py", line 121, in __getitem__
    img = self.transform(img)
  File "/home/yumkim/miniconda3/envs/upgdnew/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/yumkim/miniconda3/envs/upgdnew/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 98, in __call__
    return F.to_tensor(pic)
  File "/home/yumkim/miniconda3/envs/upgdnew/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 141, in to_tensor
    np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Image'
 

